apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: flopachat
data:
  CORS_ORIGIN: "http://marketplace.local"
  STATS_SERVICE_URL: "http://stats-service:4000"
  NODE_ENV: "production"
  MONGO_DB_NAME: "flopachat"
